07_django/review_prj/board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path("index/", views.index, name="index"),
    path("greeting/<str:name>/<str:c>", views.greeting, name="greeting"),
    path("articles/", views.article_list, name="list"),
    path("articles/new/", views.article_new, name="new"),
    path("articles/<int:id>/", views.article_detail, name="detail"),
    path("articles/<int:id>/edit", views.article_edit, name="edit"),
    path("articles/<int:id>/delete", views.article_delete, name="delete"),
]

07_django/review_prj/review_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("board/", include("board.urls")),
]

07_django/review_prj/board/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return f"{self.id} : {self.title}"

07_django/review_prj/board/views.py
from django.shortcuts import render, resolve_url, redirect, get_object_or_404
from .models import Article

def article_list(request):
    articles = Article.objects.all()
    return render(request, "board/list.html", {"articles":articles})


def article_new(request):
    if request.method == "POST":
        article = Article()
        article.title = request.POST.get("title")
        article.content = request.POST.get("content")
        article.save()
        return redirect("board:list")

    return render(request, "board/new.html")


def article_detail(request, id):
    article = get_object_or_404(Article, id=id)
    return render(request, "board/detail.html", {"article":article})


def article_edit(request, id):
    article = get_object_or_404(Article, id=id)
    if request.method == "POST":
        article.title = request.POST.get("title")
        article.content = request.POST.get("content")
        article.save()
        return redirect("board:detail")

    return render(request, "board/edit.html", {"article":article})


def article_delete(request, id):
    if request.method == "POST":
        article = get_object_or_404(Article, id=id)
        article.delete()
    return redirect("board:list")




def index(request):
    return render(request, "board/index.html")


def greeting(request, name, c):
    return render(request, "board/greeting.html", {"ireum":name, "class":c})

07_django/review_prj/board/templates/board/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>review{% block title %}{% endblock %}</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

07_django/review_prj/board/templates/board/detail.html
{% extends "board/base.html" %}

{% block title %} - detail{% endblock %}

{% block body %}
    <table>
        <tr>
            <td>
                Title
            </td>
            <td>
                Content
            </td>
        </tr>
        <tr>
            <td>
                {{ article.title }}
            </td>
            <td>
                {{ article.content }}
            </td>
        </tr>
    </table>
    <div>
    <form action="{% url 'board:delete' article.id %}" method="POST">
        {% csrf_token %}
        <button type="submit">delete</button>
    <a href="{% url 'board:list' %}"><button>list</button></a>
    <a href="{% url 'board:edit' article.id %}"><button type="submit">edit</button></a>
    </form>
    </div>
{% endblock %}

07_django/review_prj/board/templates/board/edit.html
{% extends "board/base.html" %}

{% block title %} - edit{% endblock %}

{% block body %}
    <form action="{% url 'board:edit' article.id %}" method="POST">
    {% csrf_token %}
    <table>
        <label for="title">Title : </label>
        <input type="text" name="title" id="title" value="{{ article.title }}">

        <label for="content">Content : </label>
        <textarea name="content" id="content">{{ article.content }}</textarea>
    </table>
        <button type="submit">edit</button>
    </form>
{% endblock %}

07_django/review_prj/board/templates/board/greeting.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>냠 {{ ireum }} : {{ class }}</h1>
</body>
</html>

07_django/review_prj/board/templates/board/index.html
{% extends "board/base.html" %}

{% block title %}ㄱㅁ{% endblock %}

{% block body %}
뚠뚠
{% endblock %}

07_django/review_prj/board/templates/board/list.html
{% extends "board/base.html" %}

{% block title %} - list{% endblock %}

{% block body %}
    <a href="{% url 'board:new' %}"><input type="submit" value="create"></a>
    <table>
        <tr>
            <td>ID</td>
            <td>Title</td>
        </tr>
        {% for article in articles %}
        <tr>
            <td>
                {{ article.id }}
            </td>
            <td>
                <a href="{% url 'board:detail' article.id %}">{{ article.title }}</a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

07_django/review_prj/board/templates/board/new.html
{% extends "board/base.html" %}

{% block title %} - new{% endblock %}

{% block body %}
    <form action="{% url 'board:new' %}" method="POST">
        {% csrf_token %}
        <label for="title">Title : </label>
        <input type="text" name="title" id="title">

        <label for="content">Content : </label>
        <textarea name="content" id="content"></textarea>

        <button type="submit">create</button>
    </form>
{% endblock %}