07_django/INSTA/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("users/<str:username>/", views.user_detail, name="user_detail"),
    path("follow/<str:username>/", views.toggle_follow, name="toggle_follow"),
]

07_django/INSTA/insta/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("insta/", include("posts.urls")),
    path("accounts/", include("accounts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if env dev => [...]
# if env prod => None


if settings.DEBUG: # 지금은 True
    import debug_toolbar
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

07_django/INSTA/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("create/", views.create_post, name="create_post"),
    path("<int:post_id>/update/", views.update_post, name="update_post"),
    path("<int:post_id>/create_comment/", views.create_comment, name="create_comment"),
    path("<int:post_id>/like/", views.toggle_like, name="like"),
    path("tags/<str:tag_name>/", views.tag_posts_list, name="tag_posts_list"),
]

07_django/INSTA/posts/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings

import os
ENV = os.environ.get("ENVIRONMENT", "development")

if ENV == "development":
    from faker import Faker
    hide_on_bush = Faker()


class HashTag(models.Model):
    content = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.content


class Post(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=140, unique=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts")
    tags = models.ManyToManyField(HashTag, blank=True, related_name="posts")
    # image = models.ImageField(blank=True) # pip install pillow
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)

    @classmethod
    def dummy(cls, n):
        for i in range(n):
            Post.objects.create(content=hide_on_bush.text(102))


class Image(TimeStampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = ProcessedImageField(
        processors=[ResizeToFill(600, 600)],
        upload_to="posts/images", format="JPEG", options={"quality": 90, },
        blank=True)


class Comment(TimeStampedModel):
    content = models.CharField(max_length=100)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

07_django/INSTA/posts/forms.py
from django import forms
from .models import Post, Image, Comment

class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = "__all__"
        fields = ["content"]


class ImageModelForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ["file", ]
        widgets = {
            "file": forms.FileInput(attrs={"multiple": True})
        }


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content", ]

07_django/INSTA/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponseBadRequest
from .models import Post, Image, HashTag
from .forms import PostModelForm, ImageModelForm, CommentModelForm


@login_required
@require_http_methods(["GET", "POST"])
def create_post(request):
    posts = Post.objects.all()
    if request.method == "POST":
        post_form = PostModelForm(request.POST)
        if post_form.is_valid():
            post = post_form.save(commit=False) # save를 하면 나오는 값을 post에 담아둠
            # commit=False를 쓰면 가짜 save, 저장은 하는데 넘기진 않음
            post.user = request.user
            if post not in posts:
                post.save()
            else:
                print("있어")

            # create hashtag => <input name="tags" /> #hi #ssafy #20층
            content = post_form.cleaned_data.get("content") #
            words = content.split(" ") # 띄어쓰기로 split
            for word in words:
                if word[0] == "#":
                    word = word[1:]
                    tag = HashTag.objects.get_or_create(content=word) # (HashTagObject, True or False)
                    post.tags.add(tag[0])
                    if tag[1]:
                        messages.add_message(request, messages.SUCCESS, f"{tag[0].content}를 처음으로 추가하셨어요!")


            for image in request.FILES.getlist("file"):
                request.FILES["file"] = image
                image_form = ImageModelForm(files=request.FILES)
                if image_form.is_valid():
                    image = image_form.save(commit=False)

                    image.post = post
                    image.save()
            return redirect("posts:post_list")
    else:
        post_form = PostModelForm()
    image_form = ImageModelForm()
    return render(request, "posts/form.html", {"post_form": post_form, "image_form": image_form})


@login_required
@require_http_methods(["GET", "POST"])
def update_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.user == request.user:
        if request.method == "POST":
            post_form = PostModelForm(request.POST, request.FILES, instance=post)
            if post_form.is_valid():
                post_form.save()
                #update hashtag
                post.tags.clear() # 포스트의 모든 tag 삭제
                content = post_form.cleaned_data.get("content")  #
                words = content.split(" ")  # 띄어쓰기로 split
                for word in words:
                    if word[0] == "#":
                        word = word[1:]
                        tag = HashTag.objects.get_or_create(content=word)  # (HashTagObject, True or False)
                        post.tags.add(tag[0])
                        if tag[1]:
                            messages.add_message(request, messages.SUCCESS, f"{tag[0].content}를 처음으로 추가하셨어요!")

                return redirect("posts:post_list")
        else:
            post_form = PostModelForm(instance=post)
        return render(request, "posts/form.html", {"post_form": post_form})
    else:
        # 403 : Forbidden 금지!
        return redirect("posts:post_list")


@require_GET
def post_list(request):
    posts = Post.objects.all()
    comment_form = CommentModelForm()
    return render(request, "posts/list.html", {"posts": posts, "comment_form": comment_form})


@login_required
@require_POST
def create_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comment_form = CommentModelForm(data=request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.post = post
        comment.save()
    return HttpResponseRedirect(request.META.get("HTTP_REFERER", "/insta/"))
    # TODO: else => if comment is not valid, then what?


# @login_required()
# @require_POST
# def create_like(request, post_id):
#     user = request.user
#     post = get_object_or_404(Post, id=post_id)
#     # user.like_posts.add(post) # 유저가 가진 정보를 add 하는 방법
#     post.like_users.add(user) # 포스트에 유저를 더하는 방법
#

@login_required
@require_POST
def toggle_like(request, post_id):
    if request.is_ajax():
        user = request.user
        post = get_object_or_404(Post, id=post_id)
        # if post.like_users.filter(id=user.id).exist(): # 좋아요 한 사람이 있으면 값이 나오고 없으면 빈 리스트 # exist는 좀 더 명확하게 만드는 역할
        is_active = True
        if user in post.like_users.all():
            post.like_users.remove(user)
            is_active = False
        else:
            post.like_users.add(user)
        # return HttpResponseRedirect(request.META.get("HTTP_REFERER", "/insta/"))
        return JsonResponse({"likeCount": post.like_users.count(), "is_active": is_active})
    else:
        return HttpResponseBadRequest()


@require_GET
def tag_posts_list(request, tag_name):
    tag = get_object_or_404(HashTag, content=tag_name)
    posts = tag.posts.all()
    comment_form = CommentModelForm()
    return render(request, "posts/list.html", {"posts": posts, "comment_form": comment_form, "h1": f"#{tag}를 포함한 posts입니다."})

07_django/INSTA/posts/templates/posts/_post.html
{% load bootstrap4 %}
{% load static %}

<article class="card my-3">
    {% if post.image_set.all %}
        <div id="post{{ post.id }}" class="carousel slide carousel-fade" data-ride="carousel">
            <div class="carousel-inner">
                {% for image in post.image_set.all %}
                    <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                        <img src="{{ image.file.url }}" class="d-block w-100" alt="{{ image.file }}">
                    </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#post{{ post.id }}" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#post{{ post.id }}" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    {% else %}
        {#        <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.image }}">#}
        <img src="https://picsum.photos/600/?random" class="card-img-top" alt="random-image">
    {% endif %}

    <div class="card-body">
        <!-- 좋아요 버튼 1 -->
        <form action="{% url 'posts:like' post.id %}" method="POST">
            {% csrf_token %}
            {% if user in post.like_users.all %}
                <input type="image" id="like_image" src="../../static/posts/green.png" value="green" width="30">
                {{ post.like_users.all.count }}
            {% else %}
                <input type="image" id="like_image" src="../../static/posts/empty.png" value="empty" width="30">
                {{ post.like_users.all.count }}
            {% endif %}
        </form>

        <!-- 좋아요 버튼 2 -->
        {% if user in post.like_users.all %}
            <i class="like-button fas fa-thumbs-up fa-2x activate" data-id="{{ post.id }}"></i>
{#            <input class="like-button" type="image" id="like-button" src="{% static 'posts/green.png' %}" width="30">#}
        {% else %}
            <i class="like-button fas fa-thumbs-up fa-2x" data-id="{{ post.id }}"></i>
{#            <input class="like-button" type="image" id="like-button" src="{% static 'posts/empty.png' %}" width="30">#}
        {% endif %}
        <span id="like-count-{{ post.id }}">{{ post.like_users.count }}</span>


        <p class="card-text">작성자 : <a
                href="{% url 'accounts:user_detail' post.user.username %}">{{ post.user.username }}</a></p>
        <p class="card-text">내용 : {{ post.content }}</p>

        {% if post.user == user %}
            <a href="{% url 'posts:update_post' post.id %}" class="btn btn-warning">수정</a>
        {% endif %}

        <div class="my-5">
            {% if post.comment_set.all %}
                {% for comment in post.comment_set.all %}
                    <p class="card-text">
                        <strong><a
                                href="{% url 'accounts:user_detail' comment.user.username %}">{{ comment.user.username }}</a></strong>
                        : {{ comment.content }}
                    </p>
                {% endfor %}
            {% else %}
                <p class="card-text">
                    댓글을 달아주세요!
                </p>
            {% endif %}
        </div>
        <div class="card-footer">
            <form action="{% url 'posts:create_comment' post.id %}" method="POST">
                {% csrf_token %}
                {% bootstrap_form comment_form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">댓글 달기</button>
                {% endbuttons %}
            </form>
        </div>
    </div>
</article>

07_django/INSTA/posts/templates/posts/form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block body %}
    <h1>New Post</h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {#        {{ post_form.as_p }}#}
        {#        {{ image_form.as_p }}#}
        {% bootstrap_form post_form %}
        {% if image_form %}
            {% bootstrap_form image_form show_label=False %}
        {% endif %}
        {% buttons %}
            <button type="submit" class="btn btn-secondary">Submit</button>
        {% endbuttons %}
    </form>
{% endblock %}

07_django/INSTA/posts/templates/posts/list.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body %}
    {% if h1 %}
        <h1>{{ h1 }}</h1>
    {% endif %}
    <section class="card-columns">
        {% for post in posts %}
            {% include "posts/_post.html" with post=post comment_form=comment_form %}
        {% endfor %}
    </section>
{% endblock %}