07_django/INSTA/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("users/<str:username>/", views.user_detail, name="user_detail"),
    path("follow/<str:username>/", views.toggle_follow, name="toggle_follow"),
]

07_django/INSTA/insta/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("insta/", include("posts.urls")),
    path("accounts/", include("accounts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if env dev => [...]
# if env prod => None


if settings.DEBUG: # 지금은 True
    import debug_toolbar
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

07_django/INSTA/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("create/", views.create_post, name="create_post"),
    path("<int:post_id>/update/", views.update_post, name="update_post"),
    path("<int:post_id>/create_comment/", views.create_comment, name="create_comment"),
    path("<int:post_id>/like/", views.toggle_like, name="like"),
    path("tags/<str:tag_name>/", views.tag_posts_list, name="tag_posts_list"),
]

07_django/INSTA/insta/templates/_cdns.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

07_django/INSTA/insta/templates/_messages.html
{% load bootstrap4 %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            {% bootstrap_alert message alert_type=message.tags %}
{#            <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>#}
        {% endfor %}
    </ul>
{% endif %}

07_django/INSTA/insta/templates/_navbar.html
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light px-5">
    <a class="navbar-brand" href="{% url 'posts:post_list' %}">
        <i class="fab fa-instagram"></i> | Instagram
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'posts:create_post' %}">New</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_detail' user.username %}">{{ user.username }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

07_django/INSTA/insta/templates/_scripts.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

07_django/INSTA/insta/templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% include "_cdns.html" %}
    <style>
        .activate {
            color: dodgerblue;
        }
    </style>
    <title>Insta - {% block title %}{% endblock %}</title>
</head>
<body>
{% include "_navbar.html" %}
{% include "_messages.html" %}
<div class="container">
    {% block body %}
    {% endblock %}
</div>
{% include "_scripts.html" %}
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
    function giveMeChoco(key="") {
        const chocoBox = {};
        document.cookie.split("; ").forEach(chocolate => {
            const keyval = chocolate.split("=");
            chocoBox[keyval[0]] = keyval[1];
        });
        {#return chocoBox;#}
        return key ? chocoBox[key] : chocoBox
    }

    const likeButtons = document.querySelectorAll(".like-button");

    giveMeChoco().csrftoken

    likeButtons.forEach(button => {
        button.addEventListener("click", e => {
            const postId = button.dataset.id;
            const URL = `/insta/${postId}/like/`;
            // request에 cookie 중에 csrftoken이라는 key 값을 가진 친구를 같이 보내라
            axios.defaults.xsrfCookieName = "csrftoken";
            // request에 header 중에 X-CSRFToken이라는 key 값을 가진 친구를 같이 보내라
            axios.defaults.xsrfHeaderName = "X-CSRFToken";
            // 이 request는 XHR 방식으로 보내는 것입니다.
            axios.defaults.headers.common["X-Requested-With"] = "XMLHttpRequest";
            axios.post(URL, {})
                .then(response => {
                    console.log(response)
                    const likeCountArea = document.querySelector(`#like-count-${postId}`);
                    likeCountArea.innerHTML = response.data.likeCount;

                    {#const btnClsList = e.target.classList;#}
                    {#response.data.is_active ? btnClsList.add("activate") : btnClsList.remove("activate");#}

                    if (response.data.is_active) {
                        e.target.classList.add("activate");
                    } else {
                        e.target.classList.remove("activate");
                    }
                })
        })
    });
</script>
</body>
</html>