07_django/INSTA/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("users/<str:username>/", views.user_detail, name="user_detail"),
    path("follow/<str:username>/", views.toggle_follow, name="toggle_follow"),
]

07_django/INSTA/insta/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("insta/", include("posts.urls")),
    path("accounts/", include("accounts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if env dev => [...]
# if env prod => None


if settings.DEBUG: # 지금은 True
    import debug_toolbar
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

07_django/INSTA/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class User(AbstractUser): # User는 빈 껍데기고, AbstractUser가 거의 모든 걸 가지고 있음
    # username, password, first_name, last_name, email은 기본적으로 가지고 있음
    # settings.AUTH_USER_MODEL 부분은 "self"나 "accounts.User"를 써도 됨
    followings = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followers", blank=True)

    def __str__(self):
        return f"{self.username}"

07_django/INSTA/posts/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings

import os
ENV = os.environ.get("ENVIRONMENT", "development")

if ENV == "development":
    from faker import Faker
    hide_on_bush = Faker()


class HashTag(models.Model):
    content = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.content


class Post(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=140, unique=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts")
    tags = models.ManyToManyField(HashTag, blank=True, related_name="posts")
    # image = models.ImageField(blank=True) # pip install pillow
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)

    @classmethod
    def dummy(cls, n):
        for i in range(n):
            Post.objects.create(content=hide_on_bush.text(102))


class Image(TimeStampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = ProcessedImageField(
        processors=[ResizeToFill(600, 600)],
        upload_to="posts/images", format="JPEG", options={"quality": 90, },
        blank=True)


class Comment(TimeStampedModel):
    content = models.CharField(max_length=100)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

07_django/INSTA/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
# UserCreationForm: 가입, UserChangeForm: 정보 수정, AuthenticationForm: 로그인
from .models import User


class CustomUserCreateForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ["username", "email", "first_name", "last_name"]


class CustomUserAuthenticationForm(AuthenticationForm):
    class Meta(AuthenticationForm):
        model = User


class CustomUserChaneForm(UserChangeForm):
    pass

07_django/INSTA/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.views.decorators.http import require_GET, require_POST, require_http_methods
# from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import User
from .forms import CustomUserAuthenticationForm, CustomUserCreateForm
# from django.contrib.auth import get_user_model 위의 코드랑 같은 내용
from posts.forms import CommentModelForm


@require_http_methods(["GET", "POST"])
def signup(request):
    if request.method == "POST":
        form = CustomUserCreateForm(data=request.POST) # Form은 data, file로 돼 있나?
        if form.is_valid():
            form.save()
        return redirect("posts:post_list")
    else:
        form = CustomUserCreateForm()
    return render(request, "accounts/signup.html", {"form": form})


@require_http_methods(["GET", "POST"])
def login(request):
    if request.user.is_authenticated:
        return redirect("posts:post_list")
    if request.method == "POST":
        form = CustomUserAuthenticationForm(request, data=request.POST) # 얘는 request, request.???로
        if form.is_valid():
            user = form.get_user()
            auth_login(request, form.get_user())
            messages.add_message(request, messages.SUCCESS, f"어서오세요! {user.username}")
            messages.add_message(request, messages.INFO, f"이전 접속은 {user.last_login}입니다.")
            return redirect(request.GET.get("next") or "posts:post_list")
    else:
        form = CustomUserAuthenticationForm(request)
    return render(request, "accounts/login.html", {"form": form})

@login_required
def logout(request):
    auth_logout(request)
    messages.add_message(request, messages.SUCCESS, "다음에 또 만나요")
    return redirect("posts:post_list")


def user_detail(request, username):
    user_info = User.objects.get(username=username)
    return render(request, "accounts/user_detail.html", {"user_info": user_info, "comment_form": CommentModelForm()})


@login_required
@require_POST
def toggle_follow(request, username):
    sender = request.user
    receiver = get_object_or_404(User, username=username)

    if sender != receiver:
        if receiver in sender.followings.all():
            sender.followings.remove(receiver)
        else:
            sender.followings.add(receiver)
    return HttpResponseRedirect(request.META.get("HTTP_REFERER", "/insta/"))

07_django/INSTA/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body %}
    <div class="my-3">
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-success">로그인</button>
            {% endbuttons %}

        </form>
    </div>

{% endblock %}

07_django/INSTA/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body %}
    <div class="my-3">
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-success">가입</button>
            {% endbuttons %}

        </form>
    </div>

{% endblock %}

07_django/INSTA/accounts/templates/accounts/user_detail.html
{% extends "base.html" %}
{% block body %}
    <div class="row">
        <img src="" alt="{{ user_info.username }}-profile-picture">
    </div>
    <div class="col-8">
        <h1>{{ user_info.username }}</h1>
        <div>
            <h2>내가 팔로우 - {{ user_info.followings.all.count }}</h2>
            {% if user_info.followings.all %}
                <ul>
                    {% for user in user_info.followings.all %}
                        <li>{{ user.username }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <h2>나를 팔로우 - {{ user_info.followers.all.count }}</h2>
            {% if user_info.followers.all %}
                <ul>
                    {% for user in user_info.followers.all %}
                        <li>{{ user.username }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div>
            {% if user != user_info %}
            <form action="{% url 'accounts:toggle_follow' user_info.username %}" method="POST">
                {% csrf_token %}
                {% if user_info in user.followings.all %}
                    <button type="submit" class="btn btn-danger">언팔!</button>
                {% else %}
                    <button type="submit" class="btn btn-success">팔로우!</button>
                </form>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div class="card-columns">
        {% for post in user_info.post_set.all %}
            {% include "posts/_post.html" with post=post comment_form=comment_form %}
        {% endfor %}
    </div>

{% endblock %}